---
apiVersion: v1
kind: Secret
metadata:
  name: code-secret
  namespace: code-ns
  labels:
    app: codeserver
    name: code-secret
data:
  #changeit
  PASSWORD: Y2hhbmdlaXQ=
  SUDO_PASSWORD: Y2hhbmdlaXQ=
