---
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  bggdb-deploy
  namespace: bggns
  labels:
    app:  bgg
    namespace: bggns
spec:
  selector:
    matchLabels:
      app: bgg
      name: bggdb-po
  replicas: 1
  template:
    metadata:
      name: bggdb-po
      labels:
        app:  bgg
        name: bggdb-po
    spec:
      containers:
      - name:  bggdb-container
        image:  stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort:  3306

---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
  labels:
    app: bgg
    namespace: bggdb-svc
spec:
  selector:
    app: bgg
    name: bggdb-po
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
---
