---
apiVersion: v1
kind: Service
metadata:
  name: minio-hsvc
  namespace: minio-ns
  labels:
    app: minio
    name: minio-hsvc
spec:
  clusterIP: None
  selector:
    app: minio
    name: minio-po
  ports:
  - name: minio-data
    port: 9000
    targetPort: 9000
  - name: minio-console
    port: 9090
    targetPort: 9090

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-sts
  namespace: minio-ns
  labels:
    app: minio
    name: minio-sts
spec:
  replicas: 3
  serviceName: minio-hsvc
  selector:
    matchLabels:
      app: minio
      name: minio-po
  template:
    metadata:
      name: minio-po
      labels:
        app: minio
        name: minio-po
    spec:
      containers:
      - name: minio-container
        image: bitnami/minio:2023.10.25
        imagePullPolicy: IfNotPresent
        command:
        - minio
        - server
        - --address=:9000
        - --console-address=:9090
        - http://minio-sts-{0...2}.minio-hsvc.minio-ns.svc.cluster.local/data
        envFrom:
        - configMapRef:
            name: minio-cm
        - secretRef:
            name: minio-secret
        ports:
        - name: minio-data
          containerPort: 9000
        - name: minio-console
          containerPort: 9090